# Generated by Django 5.1.3 on 2025-02-11 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orderdetail_razorpay_order_id_orderdetail_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='razorpay_order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='razorpay_payment_intent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
