# Generated by Django 5.1.3 on 2025-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video File'), ('audio', 'Audio File'), ('image', 'Image File'), ('zip', 'ZIP Archive'), ('doc', 'Document'), ('other', 'Other')], default='other', help_text='Select the type of file you are uploading', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
