# Generated by Django 5.1.3 on 2025-02-23 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_orderdetail_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='payout_status',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='platform_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='vendor_amount',
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('account_holder_name', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('ifsc_code', models.CharField(max_length=11, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PayoutBatch',
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
