# Generated by Django 5.1.6 on 2025-02-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='cashfree_beneficiary_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
